// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADSp77wy4nGhQOsoqKS2vD9zQ09wf1NRs',
    appId: '1:604940502186:web:699d9b3a94910914653cd3',
    messagingSenderId: '604940502186',
    projectId: 'literasi-ai-f67aa',
    authDomain: 'literasi-ai-f67aa.firebaseapp.com',
    storageBucket: 'literasi-ai-f67aa.firebasestorage.app',
    measurementId: 'G-BV8LH3K24S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsXe6AekkFub5yXWmvBg9tanIufD3dxf0',
    appId: '1:604940502186:android:1390def3ab90085b653cd3',
    messagingSenderId: '604940502186',
    projectId: 'literasi-ai-f67aa',
    storageBucket: 'literasi-ai-f67aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTuYSzMUtLfrC1tXcStix7uDL6oKqq0I4',
    appId: '1:604940502186:ios:2691bc1ee01d158e653cd3',
    messagingSenderId: '604940502186',
    projectId: 'literasi-ai-f67aa',
    storageBucket: 'literasi-ai-f67aa.firebasestorage.app',
    iosBundleId: 'com.example.literasiAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTuYSzMUtLfrC1tXcStix7uDL6oKqq0I4',
    appId: '1:604940502186:ios:2691bc1ee01d158e653cd3',
    messagingSenderId: '604940502186',
    projectId: 'literasi-ai-f67aa',
    storageBucket: 'literasi-ai-f67aa.firebasestorage.app',
    iosBundleId: 'com.example.literasiAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADSp77wy4nGhQOsoqKS2vD9zQ09wf1NRs',
    appId: '1:604940502186:web:d651670eb889fbcd653cd3',
    messagingSenderId: '604940502186',
    projectId: 'literasi-ai-f67aa',
    authDomain: 'literasi-ai-f67aa.firebaseapp.com',
    storageBucket: 'literasi-ai-f67aa.firebasestorage.app',
    measurementId: 'G-3PVGQN49G9',
  );
}
